version: '3'
services:
  world:
    build:
      context: ./world/
    restart: always
    ports:
      - "4000:4000"
    networks:
      - playment

  hello:
    build:
      context: ./hello/
    restart: always
    ports:
      - "3000:3000"
    networks:
      - playment

  nginx:
    build:
       context: ./nginx/
    restart: always    
    ports:
      - "80:80"
    depends_on:
      - hello
      - world
    networks:
      - playment

networks:
  playment:
    driver: bridge
